from gerapy_proxy.utils import strip_response

GERAPY_PROXY_POOL_URL = None
GERAPY_PROXY_POOL_AUTH = False
GERAPY_PROXY_POOL_USERNAME = None
GERAPY_PROXY_POOL_PASSWORD = None
GERAPY_PROXY_POOL_MIN_RETRY_TIMES = 0
GERAPY_PROXY_POOL_RANDOM_ENABLE_RATE = 1
GERAPY_PROXY_POOL_TIMEOUT = 5
GERAPY_PROXY_EXTRACT_FUNC = strip_response

GERAPY_PROXY_TUNNEL_URL = None
GERAPY_PROXY_TUNNEL_AUTH = False
GERAPY_PROXY_TUNNEL_USERNAME = None
GERAPY_PROXY_TUNNEL_PASSWORD = None
GERAPY_PROXY_TUNNEL_MIN_RETRY_TIMES = 1
GERAPY_PROXY_TUNNEL_RANDOM_ENABLE_RATE = 1
